### PR TITLE
Explicitly compare the strings

### PR DESCRIPTION
**Pull request by mikaturunen**

### CODE REVIEW

**Comment by jwerle** [comment]
@mikaturunen Good catch, but whats the point?
Unless there is worry around magic like: `({valueOf: () => 'foo'}) == 'foo'` resulting in false positives then this PR not needed.

**Comment by mikaturunen** [comment]
It's commonly thought of as the "right way" of doing things when doing if -statements in JavaScripts, they should really just kill off the == and !=.

AirBnb has done a good, solid guide on the great do's and don'ts of JavaScript:

https://github.com/airbnb/javascript#comparison-operators--equality

Does it provide any additional functionality to the implementation? Dear lord, no. But does it bring it to a nicer readability and sexier style? Sure. Explicitly making sure things work is definitely the way to go.

**Comment by jwerle** [comment]
@mikaturunen Fair point. We're quite familiar with their guidelines. In this instance it may be stylistic or preference, but that decision is left to @wellsjo.

**Comment by mikaturunen** [comment]
:+1:

**Pull request closed without merging**
